import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import SquaresTexture from "../components/textures/SquaresTexture";
import texture from '/images/texture.svg'

const Home: NextPage = () => {
  return (
    <div className="relative">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SquaresTexture className="absolute right-0" />

      <header className="py-12 px-4 max-w-screen-xl mx-auto lg:px-10">
        <Image
          src="/indebted-logo.svg"
          alt="InDebted Logo"
          width={162}
          height={30}
        />
      </header>

      <main className="px-4 max-w-screen-xl mx-auto lg:px-10">
        <section className="flex flex-col justify-between items-center grid-cols-2 pt-8 lg:flex-row">
          <div className="flex flex-col gap-4 max-w-prose">
            <span className="text-accent font-bold">EBOOK</span>
            <h1 className="text-5xl leading-tight text-primary font-bold">
              Design Engineering Handbook
            </h1>
            <p className="text-lg text-primary">
              Bring design and development closer together to improve
              collaboration, reduce friction, and innovate faster.
            </p>

            <a className="bg-accent border-2 border-accent cursor-pointer text-white font-bold py-2 px-6 mt-4 rounded-full w-max hover:text-accent hover:bg-white">
              Download now
            </a>
          </div>

          <div className="flex shadow-2xl ">
            <Image
              src="/images/design-engineering-cover.jpeg"
              alt="Design engineering Ebook cover"
              width={325}
              height={434}
              objectFit="contain"
            />
          </div>
        </section>
      </main>
    </div>
  );
};

export default Home;
